### ISSUE TITLE
What is the main benefice using realtime over standard ajax to upload files ?

### ISSUE THREAD

**Issue by rbecheras** [vote539/socketio-file-upload#23]
I i just discover your repository and I guess it's pretty cool but I don't really mean what is the main benefice using realtime over standard ajax to upload files.

Anyone can light me about that ?

**Comment by vote539** [comment]
The purpose of this project is for applications that want to use Socket.IO as their transport mechanism.  There's nothing wrong with a pure XHR solution.

**Comment by rbecheras** [comment]
OK, I understood that, so excuse me but I wanna understand what could be the pros & cons

**Comment by vote539** [comment]
Okay, well Socket.IO is more resource intensive than pure AJAX: namely, it requires the client to download the Socket.IO+Engine.IO JavaScript library.  At the same time, Socket.IO is a bit more robust, because it handles reconnections out of the box and guarantees message delivery.  One thing you can get with Socket.IO File Upload is a progress bar, which you cannot normally do with AJAX uploads.  However, with Socket.IO File Upload, you need to write your server in Node.JS: if you haven't used Node.JS before, that would be a major drawback from the Socket.IO approach.  Hope that helps.

**Comment by rbecheras** [comment]
Thank you @vote539 for your patience and explanations.
Ok so its pretty that I thought.
Thus in your opinion, the project will be fully usable when progress behaviors will be fully implemented yes?

**Comment by vote539** [comment]
The progress behaviors are implemented as of version 0.4.  If you have any issues with the progress events not functioning properly you should open a new ticket.

**Comment by rbecheras** [comment]
Thank you very much for your time @vote539
