### ISSUE TITLE
"nothing happens" when uploading the same file again with IE11

### ISSUE THREAD

**Issue by pressmob** [vote539/socketio-file-upload#37]
After uploading a file with IE11, I try to upload the same file again but it's not possible, no event is fired.
I tried to reinitialize the uploader, I delete the file before the next try, but it doesn't help.

**Comment by jarno-steeman** [comment]
I have this on Chrome(48) as well.

**Comment by jarno-steeman** [comment]
I found the problem. I wasn't using any of the .listenOn* functions because i'm using React which has its own logic to handle DOM events. So I wrote my own handler which would then send the files to .submitFiles(). I was listening for the 'change' event on the file input element but never cleared it's value after uploading. So it wouldn't fire the 'change' event after selecting the same file again because well... the value didn't change (doh).

**Comment by vote539** [comment]
Good catch; it's true that the "change" event won't be fired a second time if the user never changed the file they selected.  A good behavior would be to automatically clear the file input box upon a successful upload.  It should be easy enough for the user of this module to do that on their end by listening for one of the events like "load" or "complete".

**Comment by pressmob** [comment]
Clearing the file input box is no problem. But what, if the user don't know what he has uploaded last time and selects the same file again for upload? There is no possibility to give feedback. The user waits for finishing the upload or an error.
