### ISSUE TITLE
Multiple Dropzones

### ISSUE THREAD

**Issue by LeoCreer** [vote539/socketio-file-upload#48]
I can only use ID for drop event
I need to use class so I can have multiple dope arias on the screen.
is this possible ?

**Comment by MaffooBristol** [comment]
Why not just loop through the multiple IDs and create a new SIOFU instance
for each one?

**Comment by LeoCreer** [comment]
Im doing that its complaining about angular.js:12520 TypeError: Cannot read property 'addEventListener' of null

**Comment by MaffooBristol** [comment]
Not sure if that is anything to do with SIOFU, sounds more like the element
you're trying to apply it to is returning null. Maybe you could post a
larger snippet of your code that's not working?

**Comment by LeoCreer** [comment]
To be clear when instantiate siofu 2 times on different ID's this is what happens on the second element It does not complete or upload client.js:538 Uncaught TypeError: readyCallbacks[data.id] is not a function

The first element gets hit 2 times once with event info once without

**Comment by LeoCreer** [comment]
Sorry didn't mean to close issue.
Does siofu create a new socket id per instantiate siofu ?

**Comment by MaffooBristol** [comment]
Well, an ID is required in order for SIOFU to be able to reference it, yes. But you should be able to loop and create a new one for each ID, unless there's something whack going on with the variable scope maybe? It's really hard to know without seeing a larger portion of the code!

**Comment by bradleysmagacz** [comment]
Hey Matt,

Here is the issue we are running into. We have an ng-repeat on a datasource directive as shown here:
```
<div class="datasource" ng-repeat="($index, datasource) in datasources">
  <datasource uuid="{{datasource.datasource_uuid}}"></datasource>
</div>
```

A snippet of the datasource directive's template looks like this, where uuid is being populated from the scope: 
`<div class="datasource" class="file_drop" id="{{uuid}}" dropzone="copy">`

Inside of the datasource directive we have this code snippet (since the uuid is being passed from the parent directive, $timeout is used to wait for the digest cycle to end). We could theoretically end up with 10 or more instances of this directive, resulting in 10 or more instances of the file uploader: 
```
  var siofu = new window.SocketIOFileUpload(fileSocket.socket());
  $timeout(function() {
    siofu.listenOnDrop(document.getElementById(scope.uuid));
  });
```

Then, once a file is dragged into the directive's dropzone, this error is occuring on line 538 of 'client.js':
`Uncaught TypeError: readyCallbacks[data.id] is not a function `

**Comment by MaffooBristol** [comment]
Thanks for the extra detail Bradley!

I'm not exactly sure at the moment- and will have to investigate further, but my initial inkling is that it's more to do with the `setTimeout` and any race conditions stemming from that rather than a lack of multiple dropzone support. What happens if you put the `var siofu...` into the timeout function too? What about if you remove the setTimeout entirely (unless that completely breaks your main code)? I get the feeling there may be some disconnect between your async ways of listening to siofu events and the way siofu fills the `readyCallbacks` object. To be completely honest I'm not 100% well versed in the code as I'm not the project OP so I can only make assumptions about a lot of stuff, so possibly @vote539 may be able to shed more light on this. But I do reckon that the issue doesn't lie within classes, IDs, or Angular, but just the way your instantiation and the event listener are in separate ticks. What are your thoughts on this?

Cheers
Matt

**Comment by bradleysmagacz** [comment]
Hey Matt,

I thought it may be a race condition so I tried adding the uploader instantiation in the $timeout function to no avail.

I also tried the code below where I passed in the directive element itself as the argument to the listenOnDrop function so we didn't have to wait for the digest cycle to end:
```
var siofu = new window.SocketIOFileUpload(fileSocket.socket());
siofu.listenOnDrop(element[0]);
```

Unfortunately, for our current usage, we need to instantiate these dropzones dynamically when a new datasource directive is added.

My hunch is that adding another dropzone resets the readyCallbacks array to empty resulting in no function being available at index 0, but I'm not entirely sure.

**Comment by MaffooBristol** [comment]
That's odd that having a brand new instantiation in a brand new variable would cause any issues, seeing as `readyCallbacks` isn't going to be reset or reused in any way if it's being referenced within an entirely new object. The resetting issue you're mentioning would make sense if you were reusing the same object, which can of course cause lots of issues, but otherwise I can't really see an obvious root to the problem...

**Comment by vote539** [comment]
There should be one, and only one, client-side copy of SIOFU, assuming you have only one open socket connection.  If you create multiple instances of SIOFU on the client side, they will get confused because they have to communicate over the same socket.

You should create your SIOFU instance at the same time that you create your Socket.IO instance on the client side, and everyone should refer to the same instance.

Another thing you should consider is that Angular can make and delete elements on the fly.  So if you run `document.getElementById(uuid)`, the event binding will be attached to the current element, but as soon as `datasources` changes, the original element has the potential to go away and be replaced with an identical copy that doesn't have the SIOFU event binding anymore.

**Comment by LeoCreer** [comment]
Thank you @vote539, I figured that it only supported one SIOFU.

**Comment by MaffooBristol** [comment]
My apologies for giving incorrect info... I think I was getting confused with requiring only one SIOFU per socket. Glad you fixed the issue!
