### ISSUE TITLE
Uncaught DOMException: Failed to execute 'readAsArrayBuffer' on 'FileReader': The object is already busy reading Blobs.

### ISSUE THREAD

**Issue by DaneEveritt** [vote539/socketio-file-upload#63]
A user reported that in Chrome on Windows 10 the following error is thrown which causes the progress indicator to read 100% done while network traffic continues in the background.

I'm not sure if this is fixed by #60 or not as I haven't updated our codebase to use anything past `0.5.0`, but I can check on that later this week if that would help.

```
Uncaught DOMException: Failed to execute 'readAsArrayBuffer' on 'FileReader': The object is already busy reading Blobs.
    at x (<redacted>/js/vendor/upload/client.min.js:9:231)
    at Array.<anonymous> (<redacted>/js/vendor/upload/client.min.js:11:449)
    at n.<anonymous> (<redacted>/js/vendor/upload/client.min.js:15:179)
    at n.e.emit (<redacted>/js/vendor/socketio/socket.io.min.js:23:1606)
    at n.onevent (<redacted>/js/vendor/socketio/socket.io.min.js:22:31333)
    at n.onpacket (<redacted>/js/vendor/socketio/socket.io.min.js:22:30955)
    at n.<anonymous> (<redacted>/js/vendor/socketio/socket.io.min.js:23:2238)
    at n.e.emit (<redacted>/js/vendor/socketio/socket.io.min.js:23:1606)
    at n.ondecoded (<redacted>/js/vendor/socketio/socket.io.min.js:21:23673)
    at s.<anonymous> (<redacted>/js/vendor/socketio/socket.io.min.js:23:2238)
x @ client.min.js:9
```

**Comment by vote539** [comment]
#60 did indeed touch parts of the code relating to file progress and reading chunks of files.  It would be worth upgrading to v0.6.0 and see if anything changes.  The only reason the version number was bumped by #60 is because the *chunkDelay* setting was removed.  If your code doesn't use that setting, nothing else should break by upgrading.

**Comment by DaneEveritt** [comment]
Sounds good, just wanted to let you know that other people with the issue report Chrome on Windows 10 as well. Will report back when I push an update and see if it gets fixes.

**Comment by joshuaohana** [comment]
@DaneEveritt This was driving me nuts, for my case at least this error presented all over the place seemingly at random if I had more than one occurrence of uploader.listen on the server running at the same time. v0.5.0 and 0.6.0

**Comment by vote539** [comment]
Indeed, you have to make a `var uploader = new SocketIOFileUpload()` followed by `uploader.listen(socket)` for each connection.  Don't make one global uploader object and call `uploader.listen(socket)` on the same object for each different connection.  Really it would probably have been better to put the socket directly into the constructor to avoid the temptation to move the `new SocketIOFileUpload()` to a different scope.

If DaneEveritt can confirm that this is the problem, I'll close the ticket.

**Comment by DaneEveritt** [comment]
So, I believe I am doing this correctly, as each server has their own Upload Websocket endpoint, as seen in the code here:

https://github.com/Pterodactyl/Daemon/blob/develop/src/http/upload.js#L38

So I'm doing
```js
Uploader.listen(socket);
```

Where `socket` is `/upload/some-uuid`.

**Comment by vote539** [comment]
Ok, here's what I think might be happening.  Whenever there is a new connection, you call `this.websocket.on("connection", ...)`.  This means that you're adding a new event listener to that socket namespace every time that someone connects to your server.  However, when they disconnect from the server, you leave the event listener "hanging".  Socket.IO doesn't clean it up since it's a namespace on the global object.  If the same user comes back again, the event listener from last time is still sitting there, so then you have multiple instances of SocketIOFileUpload listening to the same connection.

I'd try doing one of the following two options:

1. Call `Socket.of("/uploads").on("connection", ...)` only once, during server startup, and direct uploads to use that namespace instead of the "upload-some-uuid" namespace.
2. Explicitly remove the socket namespace event listener when the user disconnects.

Let me know if this make sense and if it works.

**Comment by DaneEveritt** [comment]
Going to close this, as I believe it has been fixed in the latest releases.
